const flags = { afghanistan : { name: 'Afghanistan', flag: '🇦🇫' },
  albania: { name: 'Albania', flag: '🇦🇱' },
  algeria: { name: 'Algeria', flag: '🇩🇿' },
  angola: { name: 'Angola', flag: '🇦🇴' },
  antiguaandbarbuda: { name: 'Antigua and Barbuda', flag: '🇦🇬' },
  argentina: { name: 'Argentina', flag: '🇦🇷' },
  armenia: { name: 'Armenia', flag: '🇦🇲' },
  australia: { name: 'Australia', flag:'🇦🇺' },
  austria: { name: 'Austria', flag: '🇦🇹' },
  azerbaijan: { name: 'Azerbaijan', flag: '🇦🇿' },
  bahamas: { name: 'Bahamas', flag: '🇧🇸' },
  bahrain: { name: 'Bahrain', flag: '🇧🇭' },
  bangladesh: { name: 'Bangladesh', flag: '🇧🇩' },
  barbados: { name: 'Barbados', flag: '🇧🇧' },
  belarus: { name: 'Belarus', flag: '🇧🇾' },
  belgium: { name: 'Belgium', flag: '🇧🇪' },
  benin: { name: 'Benin', flag: '🇧🇯' },
  bhutan: { name: 'Bhutan', flag: '🇧🇹' },
  bolivia: { name: 'Bolivia', flag: '🇧🇴' },
  bosniaandherzegovina: { name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  botswana: { name: 'Botswana', flag: '🇧🇼' },
  brazil: { name: 'Brazil', flag: '🇧🇷' },
  brunei: { name: 'Brunei', flag: '🇧🇳' },
  bulgaria: { name: 'Bulgaria', flag: '🇧🇬' },
  burkinafaso: { name: 'Burkina Faso', flag: '🇧🇫' },
  burundi: { name: 'Burundi', flag: '🇧🇮' },
  cambodia: { name: 'Cambodia', flag: '🇰🇭' },
  cameroon: { name: 'Cameroon', flag: '🇨🇲' },
  canada: { name: 'Canada', flag: '🇨🇦' },
  caboverde: { name: 'Cabo Verde', flag: '🇨🇻' },
  centralafricanrepublic: { name: 'Central African Republic', flag: '🇨🇫' },
  chad: { name: 'Chad', flag: '🇹🇩' },
  chile: { name: 'Chile', flag: '🇨🇱' },
  china: { name: 'China', flag: '🇨🇳' },
  colombia: { name: 'Colombia', flag: '🇨🇴' },
  comoros: { name: 'Comoros', flag: '🇰🇲' },
  democraticrepublicofthecongo: { name: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  republicofthecongo: { name: 'Republic of the Congo', flag: '🇨🇬' },
  costarica: { name: 'Costa Rica', flag: '🇨🇷' },
  cotedivoire: { name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  croatia: { name: 'Croatia', flag: '🇭🇷' },
  cuba: { name: 'Cuba', flag: '🇨🇺' },
  cyprus: { name: 'Cyprus', flag: '🇨🇾' },
  czechia: { name: 'Czechia', flag: '🇨🇿' },
  denmark: { name: 'Denmark', flag: '🇩🇰' },
  djibouti: { name: 'Djibouti', flag: '🇩🇯' },
  dominica: { name: 'Dominica', flag: '🇩🇲' },
  dominicanrepublic: { name: 'Dominican Repubulic', flag: '🇩🇴' },
  ecuador: { name: 'Ecuador', flag: '🇪🇨' },
  egypt: { name: 'Egypt', flag: '🇪🇬' },
  elsalvador: { name: 'El Salvador', flag: '🇸🇻' },
  equatorialguinea: { name: 'Equatorial Guinea', flag: '🇬🇶' },
  eritrea: { name: 'Eritrea', flag: '🇪🇷' },
  estonia: { name: 'Estonia', flag: '🇪🇪' },
  eswatini: { name: 'Eswatini', flag: '🇸🇿' },
  ethiopia: { name: 'Ethiopia', flag: '🇪🇹' },
  fiji: { name: 'Fiji', flag: '🇫🇯' },
  finland: { name: 'Finland', flag: '🇫🇮' },
  france: { name: 'France', flag: '🇫🇷' },
  gabon: { name: 'Gabon', flag: '🇬🇦' },
  gambia: { name: 'Gambia', flag: '🇬🇲' },
  georgia: { name: 'Georgia', flag: '🇬🇪' },
  germany: { name: 'Germany', flag: '🇩🇪' },
  ghana: { name: 'Ghana', flag: '🇬🇭' },
  greece: { name: 'Greece', flag: '🇬🇷' },
  grenada: { name: 'Grenada', flag: '🇬🇩' },
  guatemala: { name: 'Guatemala', flag: '🇬🇹' },
  guinea: { name: 'Guinea', flag: '🇬🇳' },
  guineabissau: { name: 'Guinea Bissau', flag: '🇬🇼' },
  guyana: { name: 'Guyana', flag: '🇬🇾' },
  haiti: { name: 'Haiti', flag: '🇭🇹' },
  honduras: { name: 'Honduras', flag: '🇭🇳' },
  hungary: { name: 'Hungary', flag: '🇭🇺' },
  iceland: { name: 'Iceland', flag: '🇮🇸' },
  india: { name: 'India', flag: '🇮🇳' },
  indonesia: { name: 'Indonesia', flag: '🇮🇩' },
  iran: { name: 'Iran', flag: '🇮🇷' },
  iraq: { name: 'Iraq', flag: '🇮🇶' },
  ireland: { name: 'Ireland', flag: '🇮🇪' },
  israel: { name: 'Israel', flag: '🇮🇱' },
  italy: { name: 'Italy', flag: '🇮🇹' },
  jamaica: { name: 'Jamaica', flag: '🇯🇲' },
  japan: { name: 'Japan', flag: '🇯🇵' },
  jordan: { name: 'Jordan', flag: '🇯🇴' },
  kazakhstan: { name: 'Kazakhstan', flag: '🇰🇿' },
  kenya: { name: 'Kenya', flag: '🇰🇪' },
  kiribati: { name: 'Kiribati', flag: '🇰🇮' },
  kosovo: { name: 'Kosovo', flag: '🇽🇰' },
  kuwait: { name: 'Kuwait', flag: '🇰🇼' },
  kyrgyzstan: { name: 'Kyrgyzstan', flag: '🇰🇬' },
  laos: { name: 'Laos', flag: '🇱🇦' },
  latvia: { name: 'Latvia', flag: '🇱🇻' },
  lebanon: { name: 'Lebanon', flag: '🇱🇧' },
  lesotho: { name: 'Lesotho', flag: '🇱🇸' },
  liberia: { name: 'Liberia', flag: '🇱🇷' },
  libya: { name: 'Libya', flag: '🇱🇾' },
  liechtenstein: { name: 'Liechtenstein', flag: '🇱🇮' },
  lithuania: { name: 'Lithuania', flag: '🇱🇹' },
  luxembourg: { name: 'Luxembourg', flag: '🇱🇺' },
  madagascar: { name: 'Madagascar', flag: '🇲🇬' },
  malawi: { name: 'Malawi', flag: '🇲🇼' },
  malaysia: { name: 'Malaysia', flag: '🇲🇾' },
  maldives: { name: 'Maldives', flag: '🇲🇻' },
  mali: { name: 'Mali', flag: '🇲🇱' },
  malta: { name: 'Malta', flag: '🇲🇹' },
  marshallislands: { name: 'Marshall Islands', flag: '🇲🇭' },
  mauritania: { name: 'Mauritania', flag: '🇲🇷' },
  mauritius: { name: 'Mauritius', flag: '🇲🇺' },
  mexico: { name: 'Mexico', flag: '🇲🇽' },
  micronesia: { name: 'Micronesia', flag: '🇫🇲' },
  moldova: { name: 'Moldova', flag: '🇲🇩' },
  monaco: { name: 'Monaco', flag: '🇲🇨' },
  mongolia: { name: 'Mongolia', flag: '🇲🇳' },
  morocco: { name: 'Morocco', flag: '🇲🇦' },
  mozambique: { name: 'Mozambique', flag: '🇲🇿' },
  myanmar: { name: 'Myanmar', flag: '🇲🇲' },
  namibia: { name: 'Namibia', flag: '🇳🇦' },
  nauru: { name: 'Nauru', flag: '🇳🇷' },
  nepal: { name: 'Nepal', flag: '🇳🇵' },
  netherlands: { name: 'Netherlands', flag: '🇳🇱' },
  newzealand: { name: 'New Zealand', flag: '🇳🇿' },
  nicaragua: { name: 'Nicaragua', flag: '🇳🇮' },
  niger: { name: 'Niger', flag: '🇳🇪' },
  nigeria: { name: 'Nigeria', flag: '🇳🇬' },
  northkorea: { name: 'North Korea', flag: '🇰🇵' },
  northmacedonia: { name: 'North Macedonia', flag: '🇲🇰' },
  norway: { name: 'Norway', flag: '🇳🇴' },
  oman: { name: 'Oman', flag: '🇴🇲' },
  pakistan: { name: 'Pakistan', flag: '🇵🇰' },
  palau: { name: 'Palau', flag: '🇵🇼' },
  palestine: { name: 'Palestine', flag: '🇵🇸' },
  panama: { name: 'Panama', flag: '🇵🇦' },
  papuanewguinea: { name: 'Papua New Guinea', flag: '🇵🇬' },
  paraguay: { name: 'Paraguay', flag: '🇵🇾' },
  peru: { name: 'Peru', flag: '🇵🇪' },
  philippines: { name: 'Philippines', flag: '🇵🇭' },
  poland: { name: 'Poland', flag: '🇵🇱' },
  portugal: { name: 'Portugal', flag: '🇵🇹' },
  qatar: { name: 'Qatar', flag: '🇶🇦' },
  romania: { name: 'Romania', flag: '🇷🇴' },
  russia: { name: 'Russia', flag: '🇷🇺' },
  rwanda: { name: 'Rwanda', flag: '🇷🇼' },
  samoa: '🇼🇸',
  sanmarino: '🇸🇲',
  saotomeandprincipe: '🇸🇹',
  saudiarabia: '🇸🇦',
  senegal: '🇸🇳',
  serbia: '🇷🇸',
  seychelles: '🇸🇨',
  sierraleone: '🇸🇱',
  singapore: '🇸🇬',
  slovakia: '🇸🇰',
  slovenia: '🇸🇮',
  solomonislands: '🇸🇧',
  somalia: '🇸🇴',
  southafrica: '🇿🇦',
  southkorea: '🇰🇷',
  southsudan: '🇸🇸',
  spain: '🇪🇸',
  srilanka: '🇱🇰',
  saintkittsandnevis: '🇰🇳',
  saintlucia: '🇱🇨',
  saintvincentandgrenadines: '🇻🇨',
  sudan: '🇸🇩',
  suriname: '🇸🇷',
  sweden: '🇸🇪',
  switzerland: '🇨🇭',
  syria: '🇸🇾',
  taiwan: '🇹🇼',
  tajikistan: '🇹🇯',
  tanzania: '🇹🇿',
  thailand: '🇹🇭',
  timorleste: '🇹🇱',
  togo: '🇹🇬',
  tonga: '🇹🇴',
  trinidadandtobago: '🇹🇹',
  tunisia: '🇹🇳',
  turkey: '🇹🇷',
  turkmenistan: '🇹🇲',
  tuvalu: '🇹🇻',
  uganda: '🇺🇬',
  ukraine: '🇺🇦',
  unitedarabemirates: '🇦🇪',
  unitedkingdom: '🇬🇧',
  unitedstatesofamerica: '🇺🇸',
  uruguay: '🇺🇾',
  uzbekistan: '🇺🇿',
  vanuatu: '🇻🇺',
  vaticancity: '🇻🇦',
  venezuela: '🇻🇪',
  vietnam: '🇻🇳',
  yemen: '🇾🇪',
  zambia: '🇿🇲',
  zimbabwe: '🇿🇼'
};

module.exports = flags;